### ISSUE TITLE
Add LGBTQmap to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [pkoby/pkoby.github.io#1]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add LGBTQmap to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

I would like to suggest adding a page (JSON file) to your website, if possible, where you list the OpenStreetMap tags you are using for your website. You can then share this file with taginfo.

(sidenote: I might've only now realised the download button on the right side of the screen is for loading data in current view, not downloading/exporting data to the computer itself.)

I am aware of the other maps, but they seem to be more local/specific than is useful for taginfo.

**Comment by pkoby** [comment]
Thanks for the suggestion. I'll look into adding this to the list.

As for the load data button, do you have suggestions on what symbol or wording might be better? I'm thinking maybe a magnifying glass to "Search Area", a refresh symbol, or something similar. Or wording could be "Load Area", "Explore Data in View", or something. I don't want to auto-load on map move, because I've felt that's disruptive on other maps, but am open to feedback.

**Comment by danieldegroot2** [comment]
A :arrows_counterclockwise: refresh symbol with 'Load Area'. Alternatively, the current 'Load Places' is also okay.
Magnifying glass is usually for location search.

**Comment by pkoby** [comment]
LGBTQ+map has been added to the TagInfo Projects list. https://taginfo.openstreetmap.org/keys/lgbtq#projects
